const PDFDocument = require('pdfkit');

const createDocumentPdf = (service) => new Promise((resolve, reject) => {
  const document = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];

  document.on('data', (chunk) => chunks.push(chunk));
  document.on('end', () => resolve(Buffer.concat(chunks)));
  document.on('error', reject);

  const applicantName = service.fullName || service.parentName || service.husbandName || service.childFullName || 'Citizen';
  const serviceType = service.serviceType || 'Service Request';
  const status = service.status || 'Approved';
  const issuedDate = new Date(service.updatedAt || service.createdAt || Date.now()).toLocaleDateString();

  document.rect(0, 0, document.page.width, 92).fill('#0b4d9c');
  document.fillColor('#ffffff').font('Helvetica-Bold').fontSize(20).text('E-KEBELE SERVICE PORTAL', 50, 30);
  document.font('Helvetica').fontSize(10).text('Official Digital Service Document', 50, 60);

  document.fillColor('#222222').font('Helvetica-Bold').fontSize(12).text('Application Details', 50, 125);
  document.font('Helvetica').fontSize(11);
  document.text(`Application ID: ${service.applicationId}`, 50, 155);
  document.text(`Applicant Name: ${applicantName}`, 50, 177);
  document.text(`Service Type: ${serviceType}`, 50, 199);
  document.text(`Status: ${status}`, 50, 221);
  document.text(`Issued Date: ${issuedDate}`, 50, 243);

  document.lineWidth(1).strokeColor('#10b981').rect(50, 280, 495, 52).stroke();
  document.fillColor('#047857').font('Helvetica-Bold').fontSize(14).text('STATUS: APPROVED AND VERIFIED', 125, 300);

  document.fillColor('#777777').font('Helvetica').fontSize(9)
    .text('Electronically generated by the E-Kebele Service Portal.', 50, 735)
    .text('Valid without a physical stamp.', 50, 750);

  document.end();
});

module.exports = createDocumentPdf;
