const mongoose = require('mongoose');

const serviceRequestSchema = new mongoose.Schema({
  fullName: { type: String },
  middleName: { type: String },
  lastName: { type: String },
  gender: { type: String },
  dateOfBirth: { type: String },
  placeOfBirth: { type: String },
  placeOfBirthRegion: { type: String },
  placeOfBirthZone: { type: String },
  placeOfBirthWoreda: { type: String },
  placeOfBirthKebele: { type: String },
  nationality: { type: String },
  occupation: { type: String },
  previousResidenceRegion: { type: String },
  previousResidenceZone: { type: String },
  previousResidenceWoreda: { type: String },
  previousResidenceKebele: { type: String },
  previousResidenceAddress: { type: String },
  phoneNumber: { type: String },
  email: { type: String, trim: true, lowercase: true },
  emergencyContactName: { type: String },
  emergencyPhone: { type: String },
  region: { type: String },
  nationalId: { type: String },
  applicationId: { type: String, unique: true, required: true },
  paymentAmount: { type: Number, default: 150 },
  paymentStatus: { type: String, default: 'Unpaid' },
  paymentRef: { type: String },
  paymentPhone: { type: String },
  paymentVerifiedAt: { type: Date },
  paymentVerifiedBy: { type: String },
  amountPaid: { type: Number },
  currency: { type: String, default: 'ETB' },
  zone: { type: String },
  woreda: { type: String },
  kebele: { type: String },
  residenceAddress: { type: String },
  serviceType: { type: String, required: true },
  passportPhoto: { type: String },
  birthCertificate: { type: String },
  deathCertificate: { type: String },
  divorceDocument: { type: String },
  marriageCertificate: { type: String },
  residenceProof: { type: String },
  webcamPhoto: { type: String },
  husbandName: { type: String },
  husbandId: { type: String },
  husbandPhone: { type: String },
  husbandPhoto: { type: String },
  witness1IdDocument: { type: String },
  witness2IdDocument: { type: String },
  witness3IdDocument: { type: String },
  marriageCertPhoto: { type: String },
  wifeName: { type: String },
  wifeId: { type: String },
  wifePhone: { type: String },
  wifePhoto: { type: String },
  marriageType: { type: String },
  marriageDate: { type: String },
  placeOfMarriage: { type: String },
  kebeleWoreda: { type: String },
  husbandWitness: { type: String },
  wifeWitness: { type: String },
  details: { type: String, default: '' },
  userId: { type: String },
  status: { type: String, default: 'PENDING_OFFICER' },
  createdAt: { type: Date, default: Date.now }
}, { strict: false, timestamps: true });

module.exports = mongoose.model('ServiceRequest', serviceRequestSchema);